### ISSUE TITLE
When using push function to add data to file, it says JSONErrorException.

### ISSUE THREAD

**Issue by jprasuk112** [josantonius/php-json#25]
file content before push,

```
{
    "data": []
}

``` 

file content after push

```
{
    "data": [
        {
            "key": "value"
        }
    ]
}]
}

``` 
It adds 2 closing brackets at the end. this cause JSONErrorException when push next time

**Comment by josantonius** [comment]
There doesn't seem to be any issue. How did you do it?

```php
$jsonFile->set(['data' => []]);

$jsonFile->push(['key' => 'value'], 'data');
$jsonFile->push(['foo' => 'value'], 'data');

$jsonFile->get();
```
```json
{
    "data": [
        {
            "key": "value"
        },
        {
            "foo": "value"
        }
    ]
}
```

**Comment by jprasuk112** [comment]
Did exactly same, but sometimes the json file format changes to, the one i mentioned.
This is happening when multiple requests call push at same time.
Is there anything we can do in this case?

**Comment by josantonius** [comment]
To investigate this issue and apply any potential solutions, I would need you to provide me with a test environment where I can replicate the situation.

However, it's worth mentioning that this library was not designed with concurrent request handling in mind, and I'm not sure if I want to implement and maintain this functionality. I would recommend exploring more appropriate methods for managing concurrency, such as using flock(), semaphores, or databases.
